import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  HennyPenny64: {
    fontFamily: 'HennyPenny-Regular',
    fontSize: 64,
    fontWeight: '400',
    alignSelf: 'center',
    marginTop: 35,
  },
  HennyPenny30: {
    fontFamily: 'HennyPenny-Regular',
    fontSize: 30,
    fontWeight: '400',
    marginRight: 9,
    color: 'black',
  },
  Robotoheader: {
    fontFamily: 'Roboto-Reguler',
    fontSize: 36,
    color: 'white',
    alignSelf: 'center',
    fontWeight: '700',
    marginTop: 30,
  },
  Robotosubheader: {
    fontFamily: 'Roboto-Normal',
    fontSize: 16,
    color: 'white',
    fontWeight: '400',
    alignSelf: 'center',
    marginTop: 18,
  },
  Roboto12White: {
    color: '#FFF',
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: 12,
  },
  roboto12whiteflexend: {
    fontFamily: 'Roboto-Regular',
    fontSize: 12,
    color: 'white',
    marginBottom: 15,
    alignSelf: 'flex-end',
    paddingRight: 50,
  },
  Roboto8white: {
    fontFamily: 'Roboto-Regular',
    fontSize: 8,
    color: 'white',
    fontWeight: '500',
  },
  caudex36white: {
    fontFamily: 'Caudex-Regular',
    fontSize: 36,
    fontWeight: '400',
    marginRight: 9,
    color: 'white',
  },
  caudex24black: {
    fontFamily: 'Caudex-Regular',
    fontSize: 24,
    fontWeight: '700',
    color: 'black',
  },
  Roboto10: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: 10,
  },
  Roboto8: {
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: 8,
  },
  Roboto14center: {
    fontFamily: 'Roboto-Regular',
    fontSize: 14,
    fontWeight: '400',
  },
  Roboto14w400: {
    fontFamily: 'Roboto-Regular',
    fontSize: 14,
    fontWeight: '400',
    color: 'white',
  },
  Roboto12blackcenter: {
    fontFamily: 'Roboto-Regular',
    fontSize: 12,
    fontWeight: '400',
    color: 'black',
    alignSelf: 'center',
  },
  Roboto12green: {
    color: '#304B3B',
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: 12,
  },
  Roboto24green: {
    color: '#304B3B',
    fontFamily: 'Roboto-Regular',
    fontWeight: '700',
    fontSize: 24,
    marginLeft: 5,
  },
  Roboto20center: {
    fontFamily: 'Roboto-Regular',
    fontSize: 20,
    fontWeight: '700',
    color: 'black',
  },
  Roboto13: {
    fontFamily: 'Roboto-Regular',
    fontSize: 13,
    fontWeight: '400',
  },
  Roboto12black: {
    color: 'black',
    fontFamily: 'Roboto-Regular',
    fontWeight: '400',
    fontSize: 12,
  },
});
